# Generated by Django 5.2.7 on 2025-11-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default.jpg', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
